### PR TITLE
Add condition checkers (to be used by tests)

### PR DESCRIPTION
**Pull request by alexeykazakov**
Extracted from https://github.com/codeready-toolchain/member-operator/pull/30

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@xcoulon tests for tests? :)

**Comment by xcoulon** [comment]
> @xcoulon tests for tests? :)

yes, why not? :)

**Comment by alexeykazakov** [comment]
Should I then add a test for the test for the test? ;)

**Comment by xcoulon** [comment]
> Should I then add a test for the test for the test? ;)

as many levels as you want ;)
jokes aside, is there something wrong with adding tests for such functions? Just to make sure they behave as expected

**Comment by xcoulon** [comment]
thanks for adding some tests in https://github.com/codeready-toolchain/toolchain-common/pull/17/commits/bfa1cc7d77cb0bd506e5cb9f8ce05194981c163d @alexeykazakov ;)

**Comment by alexeykazakov** [comment]
I just thought that maybe it would be overkill. Every usage of that function in tests would be a test for those helpers. But if you insist... https://github.com/codeready-toolchain/toolchain-common/pull/17/commits/bfa1cc7d77cb0bd506e5cb9f8ce05194981c163d

**Pull request merged**
