### PR TITLE
build: use Codecov GitHub Action

### PR DESCRIPTION
**Pull request by xcoulon**
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
@MatousJobanek @alexeykazakov I wonder if we could switch from OpenShift CI to GitHub Action for our "build" and "test with coverage" jobs, and use the [codecov-action](https://github.com/codecov/codecov-action) to upload the coverage reports on codecov.io. 
WDYT?

**Review by alexeykazakov — APPROVED** [review]
Nice! But shouldn't we also remove report upload from our make target?

**Comment by alexeykazakov** [comment]
Ah.. this is only about uploading the report from master... we still need to get the report for PRs, right?

**Comment by xcoulon** [comment]
> Nice! But shouldn't we also remove report upload from our make target?

yes, that's right ;)

**Comment by xcoulon** [comment]
> Ah.. this is only about uploading the report from master... we still need to get the report for PRs, right?

hmm, no, it should work in both cases, since the jobs are triggered for 
```
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master
 ```

**Comment by xcoulon** [comment]
> > Nice! But shouldn't we also remove report upload from our make target?
> 
> yes, that's right ;)

I suggest I remove this makefile goal once the OpenShift CI job has be deleted: https://github.com/openshift/release/pull/19022

**Pull request merged**
