### PR TITLE
KUBESAW-10: Rename the ToolchainCluster controller to ToolchainCluster_cache controller

### PR DESCRIPTION
**Pull request by fbm3307**
This is to Rename the ToolchainCluster controller to ToolchainCluster_cache controller

PRs in other related repos:
Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/999
Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/550

Other repo PRs where the only change is to update the go.mod dependency
Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/418
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/932
Sandbox-sre - https://github.com/codeready-toolchain/sandbox-sre/pull/1633

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
LGTM

**Review by MatousJobanek — COMMENTED** [review]
When you look at our current naming patterns of the packages, we usually don't use the underscore there. 
Take a look for example here: https://github.com/codeready-toolchain/host-operator/tree/master/controllers the packages of the controllers use one string, I would keep it consistent and name the package `toolchainclustercache` instead.

**Comment by fbm3307** [comment]
> When you look at our current naming patterns of the packages, we usually don't use the underscore there. Take a look for example here: https://github.com/codeready-toolchain/host-operator/tree/master/controllers the packages of the controllers use one string, I would keep it consistent and name the package `toolchainclustercache` instead.

@MatousJobanek Yea i saw that, but somehow since the name was too long i thought to add a underscore, removed it now.

**Review by MatousJobanek — COMMENTED** [review]
could you please update also the logger that is used in the `Reconcile` function of the controller by appending the "cache" name? 
see for example: https://github.com/codeready-toolchain/host-operator/blob/master/controllers/spacebindingcleanup/spacebinding_cleanup_controller.go#L58

**Comment by fbm3307** [comment]
> could you please update also the logger that is used in the `Reconcile` function of the controller by appending the "cache" name? see for example: https://github.com/codeready-toolchain/host-operator/blob/master/controllers/spacebindingcleanup/spacebinding_cleanup_controller.go#L58

added it

**Pull request merged**
