### PR TITLE
feat: add support for patching service account resources in member operator

### PR DESCRIPTION
**Pull request by mfrancisc**
Add patch support for SA objects.

Jira: https://issues.redhat.com/browse/SANDBOX-87

Related PR: https://github.com/codeready-toolchain/member-operator/pull/453

### CODE REVIEW

**Review by rajivnathan — APPROVED** [review]
Looks good. You could also add a couple of test cases to address the codecov warnings for the cases when labels/annotations were not set on the original object.

**Comment by mfrancisc** [comment]
@rajivnathan done. please see https://github.com/codeready-toolchain/toolchain-common/pull/317/commits/bd5dd82c70cbca5acccde73e9f731bfd6fa6399e

thanks!

**Comment by rajivnathan** [comment]
Nice! 👍

**Review by xcoulon — APPROVED** [review]

**Review by MatousJobanek — APPROVED** [review]
cool :+1:

**Pull request merged**
